### ISSUE TITLE
Gatsby page goes blank in IE11

### ISSUE THREAD

**Issue by SimonIMG** [devjmetivier/gatsby-plugin-page-progress#72]
**Describe the bug**
All pages that use `gatsby-plugin-page-progress` go completely blank in IE. Works fine in other browsers.

The console shows the error:

```
Object doesn't support property or method 'assign'
```

The only way to get it working is to add `gatsby-plugin-polyfill-io` to _gatsby-config,js_ which is a bit of a hit to performance.

**To Reproduce**
1. Add `gatsby-plugin-page-progress` to a Gatsby V2 site
1. Launch the site (either `gatsby develop` or a proper build of the site) in IE11 and navigate to a page with the progress bar enabled.

**Expected behavior**
Page displayed as normal.

**Actual behaviour**
- Webpage flashes up for a split second, then goes white.
- `<div id="___gatsby"></div>` is empty.
- `Object doesn't support property or method 'assign'`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE11

**Comment by devjmetivier** [comment]
Hello! We could probably fix this with just transpiling it through babel more aggressively to support IE11. That way you don't have to layer a polyfill on top of your app to get it working.

Shouldn't take long but I just have to find some time to play around with babel.

**Comment by devjmetivier** [comment]
Alright so it turns out babel wasn't as magical as I thought it was ¯\_(ツ)_/¯ I thought it did DOM polyfills but I guess it doesn't.

I threw a few bits of code in from MDN and nothing seems to crash in IE11 on my end now. The one caveat is that I can't get the progress indicator to actually **work**. Something about the way the width is being calculated is equating it to be **NaN**. Can't seem to narrow down the issue, but I'm not gonna spend an incredible amount of time with it because it's IE.

Good thing is I got it to stop breaking IE, so I hope this update helps!

https://www.npmjs.com/package/gatsby-plugin-page-progress
https://unpkg.com/browse/gatsby-plugin-page-progress@2.0.16/

`v2.0.16`
