### ISSUE TITLE
includesPaths/excludesPaths property bug

### ISSUE THREAD

**Issue by kxdang** [devjmetivier/gatsby-plugin-page-progress#75]
**Describe the bug**
When using the `includesPaths` and `excludesPaths` property, I found that the progress bar wouldn't show.
However, when I used `inlcudesPath` and `excludesPath` property, the progress bar ends up showing on all my pages

**To Reproduce**
On my blog: lines 24-25 contains the setup for the Gatsby plugin
https://github.com/kxdang/kiendang.me/blob/master/gatsby-config.js

**Expected behavior**
I was hoping to exclude the bar on my  `about` and `now` pages on my blog and include only the blog posts
├── src
│   ├── pages
│        └── about
│        └── now

**Additional context**
I may have completely written the regex wrong and must have messed up somewhere. I was hoping to create an issue for help or guidance of how to fix my issue. Any directions or help would be greatly appreciated!

Thank you :)

**Comment by devjmetivier** [comment]
Hey Kien 👋🏻

Thanks for opening an issue. I made a PR on your repo in question with some information that will hopefully fix your issue along with another comment that might be helpful [here](https://github.com/kxdang/kiendang.me/pull/5). Fortunately it looks as though the plugin is working correctly and the options you passed were misspelled.

Please let me know if there's anything more I can maybe do to help! If you feel like your issue has been solved, feel free to close this issue. Otherwise we'll keep it open and keep working at it.

Thanks!
